cmd_/sources/linux-4.18.5/tools/objtool/help.o := gcc -Wp,-MD,/sources/linux-4.18.5/tools/objtool/.help.o.d -Wp,-MT,/sources/linux-4.18.5/tools/objtool/help.o -Wbad-function-cast -Wdeclaration-after-statement -Wformat-security -Wformat-y2k -Winit-self -Wmissing-declarations -Wmissing-prototypes -Wnested-externs -Wno-system-headers -Wold-style-definition -Wpacked -Wredundant-decls -Wshadow -Wstrict-prototypes -Wswitch-default -Wswitch-enum -Wundef -Wwrite-strings -Wformat -Wstrict-aliasing=3 -ggdb3 -Wall -Wextra -std=gnu99 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -fPIC -O6 -Werror -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -I/sources/linux-4.18.5/tools/include/ -I/sources/linux-4.18.5/include/uapi -I/sources/linux-4.18.5/include -D"BUILD_STR(s)=$(pound)s" -c -o /sources/linux-4.18.5/tools/objtool/help.o help.c

source_/sources/linux-4.18.5/tools/objtool/help.o := help.c

deps_/sources/linux-4.18.5/tools/objtool/help.o := \
  /usr/include/stdc-predef.h \
  /usr/include/stdio.h \
  /usr/include/bits/libc-header-start.h \
  /usr/include/features.h \
  /usr/include/sys/cdefs.h \
  /usr/include/bits/wordsize.h \
  /usr/include/bits/long-double.h \
  /usr/include/gnu/stubs.h \
  /usr/include/gnu/stubs-64.h \
  /usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/include/stddef.h \
  /usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/include/stdarg.h \
  /usr/include/bits/types.h \
  /usr/include/bits/typesizes.h \
  /usr/include/bits/types/__fpos_t.h \
  /usr/include/bits/types/__mbstate_t.h \
  /usr/include/bits/types/__fpos64_t.h \
  /usr/include/bits/types/__FILE.h \
  /usr/include/bits/types/FILE.h \
  /usr/include/bits/types/struct_FILE.h \
  /usr/include/bits/types/cookie_io_functions_t.h \
  /usr/include/bits/stdio_lim.h \
  /usr/include/bits/sys_errlist.h \
  /usr/include/bits/stdio.h \
  /usr/include/bits/stdio2.h \
  /usr/include/stdlib.h \
  /usr/include/bits/waitflags.h \
  /usr/include/bits/waitstatus.h \
  /usr/include/bits/floatn.h \
  /usr/include/bits/floatn-common.h \
  /usr/include/bits/types/locale_t.h \
  /usr/include/bits/types/__locale_t.h \
  /usr/include/sys/types.h \
  /usr/include/bits/types/clock_t.h \
  /usr/include/bits/types/clockid_t.h \
  /usr/include/bits/types/time_t.h \
  /usr/include/bits/types/timer_t.h \
  /usr/include/bits/stdint-intn.h \
  /usr/include/endian.h \
  /usr/include/bits/endian.h \
  /usr/include/bits/byteswap.h \
  /usr/include/bits/uintn-identity.h \
  /usr/include/sys/select.h \
  /usr/include/bits/select.h \
  /usr/include/bits/types/sigset_t.h \
  /usr/include/bits/types/__sigset_t.h \
  /usr/include/bits/types/struct_timeval.h \
  /usr/include/bits/types/struct_timespec.h \
  /usr/include/bits/select2.h \
  /usr/include/bits/pthreadtypes.h \
  /usr/include/bits/thread-shared-types.h \
  /usr/include/bits/pthreadtypes-arch.h \
  /usr/include/alloca.h \
  /usr/include/bits/stdlib-bsearch.h \
  /usr/include/bits/stdlib-float.h \
  /usr/include/bits/stdlib.h \
  /usr/include/string.h \
  /usr/include/strings.h \
  /usr/include/bits/strings_fortified.h \
  /usr/include/bits/string_fortified.h \
  /sources/linux-4.18.5/tools/include/linux/string.h \
  /sources/linux-4.18.5/tools/include/linux/types.h \
  /usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/include/stdbool.h \
  /usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/include/stdint.h \
  /usr/include/stdint.h \
  /usr/include/bits/wchar.h \
  /usr/include/bits/stdint-uintn.h \
  /usr/include/asm/types.h \
  /sources/linux-4.18.5/include/uapi/asm-generic/types.h \
  /sources/linux-4.18.5/include/uapi/asm-generic/int-ll64.h \
  /usr/include/asm/bitsperlong.h \
  /sources/linux-4.18.5/tools/include/asm-generic/bitsperlong.h \
  /sources/linux-4.18.5/tools/include/uapi/asm-generic/bitsperlong.h \
  /usr/include/asm/posix_types.h \
  /usr/include/asm/posix_types_64.h \
  /sources/linux-4.18.5/include/uapi/asm-generic/posix_types.h \
  /usr/include/termios.h \
  /usr/include/bits/termios.h \
  /usr/include/sys/ttydefaults.h \
  /usr/include/sys/ioctl.h \
  /usr/include/bits/ioctls.h \
  /usr/include/asm/ioctls.h \
  /sources/linux-4.18.5/include/uapi/asm-generic/ioctls.h \
  /sources/linux-4.18.5/include/uapi/linux/ioctl.h \
  /usr/include/asm/ioctl.h \
  /sources/linux-4.18.5/include/uapi/asm-generic/ioctl.h \
  /usr/include/bits/ioctl-types.h \
  /usr/include/sys/stat.h \
  /usr/include/bits/stat.h \
  /usr/include/bits/statx.h \
  /usr/include/unistd.h \
  /usr/include/bits/posix_opt.h \
  /usr/include/bits/environments.h \
  /usr/include/bits/confname.h \
  /usr/include/bits/getopt_posix.h \
  /usr/include/bits/getopt_core.h \
  /usr/include/bits/unistd.h \
  /usr/include/dirent.h \
  /usr/include/bits/dirent.h \
  /usr/include/bits/posix1_lim.h \
  /usr/include/bits/local_lim.h \
  /sources/linux-4.18.5/include/uapi/linux/limits.h \
  subcmd-util.h \
  help.h \
  exec-cmd.h \

/sources/linux-4.18.5/tools/objtool/help.o: $(deps_/sources/linux-4.18.5/tools/objtool/help.o)

$(deps_/sources/linux-4.18.5/tools/objtool/help.o):
