'\" t
.TH "NSS\-SYSTEMD" "8" "" "systemd 239" "nss-systemd"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------


  

  

  .SH "NAME"
nss-systemd, libnss_systemd.so.2 \- Provide UNIX user and group name resolution for dynamic users and groups\&.


  .SH "SYNOPSIS"

    .PP
libnss_systemd\&.so\&.2

  

  .SH "DESCRIPTION"

    

    .PP
\fBnss\-systemd\fR
is a plug\-in module for the GNU Name Service Switch (NSS) functionality of the GNU C Library (\fBglibc\fR), providing UNIX user and group name resolution for dynamic users and groups allocated through the
\fIDynamicUser=\fR
option in systemd unit files\&. See
\fBsystemd.exec\fR(5)
for details on this option\&.


    .PP
This module also ensures that the root and nobody users and groups (i\&.e\&. the users/groups with the UIDs/GIDs 0 and 65534) remain resolvable at all times, even if they aren\*(Aqt listed in
/etc/passwd
or
/etc/group, or if these files are missing\&.


    .PP
To activate the NSS module, add
systemd
to the lines starting with
passwd:
and
group:
in
/etc/nsswitch\&.conf\&.


    .PP
It is recommended to place
systemd
after the
files
or
compat
entry of the
/etc/nsswitch\&.conf
lines so that
/etc/passwd
and
/etc/group
based mappings take precedence\&.

  

  .SH "EXAMPLE"

    

    .PP
Here is an example
/etc/nsswitch\&.conf
file that enables
\fBnss\-systemd\fR
correctly:


    
.sp
.if n \{\
.RS 4
.\}
.nf
passwd:         compat mymachines \fBsystemd\fR
group:          compat mymachines \fBsystemd\fR
shadow:         compat

hosts:          files mymachines resolve [!UNAVAIL=return] dns myhostname
networks:       files

protocols:      db files
services:       db files
ethers:         db files
rpc:            db files

netgroup:       nis
.fi
.if n \{\
.RE
.\}
.sp


  

  .SH "SEE ALSO"

    
    .PP
\fBsystemd\fR(1),
\fBsystemd.exec\fR(5),
\fBnss-resolve\fR(8),
\fBnss-myhostname\fR(8),
\fBnss-mymachines\fR(8),
\fBnsswitch.conf\fR(5),
\fBgetent\fR(1)

  

