/*
 !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
 This file was autogenerated by:
 /sources/perl-5.28.0/miniperl ../bin/enc2xs -Q -o ma_05_t.c -f ma_05_t.fnm
 enc2xs VERSION 2.21
*/
extern encode_t MacChineseSimp_encoding;
