#! /bin/sh
test "${ZSH_VERSION+set}" = set && alias -g '${1+"$@"}'='"$@"'
cd '/sources/autoconf-2.69/tests'
exec ${CONFIG_SHELL-/bin/sh} "/sources/autoconf-2.69/tests/./testsuite" -v -d  29 ${1+"$@"}
exit 1
