#! /bin/sh
test "${ZSH_VERSION+set}" = set && alias -g '${1+"$@"}'='"$@"'
cd '/sources/libtool-2.4.6/tests'
exec ${CONFIG_SHELL-/bin/sh} "/sources/libtool-2.4.6/tests/testsuite" -v -d  MAKE='make' CC='gcc' CFLAGS='-g -O2' CPP='gcc -E' CPPFLAGS='' LD='/usr/bin/ld -m elf_x86_64' LDFLAGS='' LIBS='' LN_S='ln -s' NM='/usr/bin/nm -B' RANLIB='ranlib' AR='ar' EGREP='/bin/grep -E' FGREP='/bin/grep -F' GREP='/bin/grep' SED='/bin/sed' STRIP='strip' lt_INSTALL='/usr/bin/install -c' MANIFEST_TOOL=':' OBJEXT='o' EXEEXT='' SHELL='/bin/sh' CONFIG_SHELL='/bin/sh' CXX='g++' CXXFLAGS='-g -O2' CXXCPP='g++ -E' F77='' FFLAGS='' FC='' FCFLAGS='' GCJ='' GCJFLAGS='-g -O2' lt_cv_with_aix_soname='aix' lt_cv_to_host_file_cmd='func_convert_file_noop' lt_cv_to_tool_file_cmd='func_convert_file_noop' _lt_pkgdatadir='/sources/libtool-2.4.6' LIBTOOLIZE='/sources/libtool-2.4.6/libtoolize' LIBTOOL='/sources/libtool-2.4.6/libtool' tst_aclocaldir='/sources/libtool-2.4.6/m4' 102 ${1+"$@"}
exit 1
