#! /bin/sh
test "${ZSH_VERSION+set}" = set && alias -g '${1+"$@"}'='"$@"'
cd '/mnt/lfs/sources/tar-1.30/tests'
exec ${CONFIG_SHELL-/bin/sh} "/mnt/lfs/sources/tar-1.30/tests/./testsuite" -v -d  92 ${1+"$@"}
exit 1
