/*
 !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
 This file was autogenerated by:
 /mnt/lfs/sources/perl-5.28.0/miniperl ../bin/enc2xs -Q -o eu_01_t.c -f eu_01_t.fnm
 enc2xs VERSION 2.21
*/
extern encode_t euc_jp_encoding;
