/*
 !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
 This file was autogenerated by:
 /sources/perl-5.28.0/miniperl ../bin/enc2xs -Q -o ji_02_t.c -f ji_02_t.fnm
 enc2xs VERSION 2.21
*/
extern encode_t jis0201_raw_encoding;
