/*
 !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
 This file was autogenerated by:
 /mnt/lfs/sources/perl-5.28.0/miniperl ../bin/enc2xs -Q -o ji_03_t.c -f ji_03_t.fnm
 enc2xs VERSION 2.21
*/
extern encode_t jis0208_raw_encoding;
