'\" t
.TH "SYSTEMD\&.TIMER" "5" "" "systemd 239" "systemd.timer"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------

  

  

  .SH "NAME"
systemd.timer \- Timer unit configuration


  .SH "SYNOPSIS"

    .PP
\fItimer\fR\&.timer

  

  .SH "DESCRIPTION"

    

    .PP
A unit configuration file whose name ends in
\&.timer
encodes information about a timer controlled and supervised by systemd, for timer\-based activation\&.


    .PP
This man page lists the configuration options specific to this unit type\&. See
\fBsystemd.unit\fR(5)
for the common options of all unit configuration files\&. The common configuration items are configured in the generic [Unit] and [Install] sections\&. The timer specific configuration options are configured in the [Timer] section\&.


    .PP
For each timer file, a matching unit file must exist, describing the unit to activate when the timer elapses\&. By default, a service by the same name as the timer (except for the suffix) is activated\&. Example: a timer file
foo\&.timer
activates a matching service
foo\&.service\&. The unit to activate may be controlled by
\fIUnit=\fR
(see below)\&.


    .PP
Note that in case the unit to activate is already active at the time the timer elapses it is not restarted, but simply left running\&. There is no concept of spawning new service instances in this case\&. Due to this, services with
\fIRemainAfterExit=\fR
set (which stay around continuously even after the service\*(Aqs main process exited) are usually not suitable for activation via repetitive timers, as they will only be activated once, and then stay around forever\&.

  

  .SH "IMPLICIT DEPENDENCIES"

    

    .PP
The following dependencies are implicitly added:


    
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Timer units automatically gain a
\fIBefore=\fR
dependency on the service they are supposed to activate\&.
.RE
  

  .SH "AUTOMATIC DEPENDENCIES"

    

    .SS "Implicit Dependencies"

      

      .PP
There are no implicit dependencies for timer units\&.

    

    .SS "Default Dependencies"

      

      .PP
The following dependencies are added unless
\fIDefaultDependencies=no\fR
is set:


      
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Timer units will automatically have dependencies of type
\fIRequires=\fR
and
\fIAfter=\fR
on
sysinit\&.target, a dependency of type
\fIBefore=\fR
on
timers\&.target, as well as
\fIConflicts=\fR
and
\fIBefore=\fR
on
shutdown\&.target
to ensure that they are stopped cleanly prior to system shutdown\&. Only timer units involved with early boot or late system shutdown should disable the
\fIDefaultDependencies=\fR
option\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Timer units with at least one
\fIOnCalendar=\fR
directive will have an additional
\fIAfter=\fR
dependency on
time\-sync\&.target
to avoid being started before the system clock has been correctly set\&.
.RE
    
  

  .SH "OPTIONS"

    

    .PP
Timer files must include a [Timer] section, which carries information about the timer it defines\&. The options specific to the [Timer] section of timer units are the following:


    

      .PP
\fIOnActiveSec=\fR, \fIOnBootSec=\fR, \fIOnStartupSec=\fR, \fIOnUnitActiveSec=\fR, \fIOnUnitInactiveSec=\fR
.RS 4

        
        
        
        
        

        Defines monotonic timers relative to different starting points:
\fIOnActiveSec=\fR
defines a timer relative to the moment the timer itself is activated\&.
\fIOnBootSec=\fR
defines a timer relative to when the machine was booted up\&.
\fIOnStartupSec=\fR
defines a timer relative to when systemd was first started\&.
\fIOnUnitActiveSec=\fR
defines a timer relative to when the unit the timer is activating was last activated\&.
\fIOnUnitInactiveSec=\fR
defines a timer relative to when the unit the timer is activating was last deactivated\&.
.sp


        Multiple directives may be combined of the same and of different types\&. For example, by combining
\fIOnBootSec=\fR
and
\fIOnUnitActiveSec=\fR, it is possible to define a timer that elapses in regular intervals and activates a specific service each time\&.
.sp


        The arguments to the directives are time spans configured in seconds\&. Example: "OnBootSec=50" means 50s after boot\-up\&. The argument may also include time units\&. Example: "OnBootSec=5h 30min" means 5 hours and 30 minutes after boot\-up\&. For details about the syntax of time spans, see
\fBsystemd.time\fR(7)\&.
.sp


        If a timer configured with
\fIOnBootSec=\fR
or
\fIOnStartupSec=\fR
is already in the past when the timer unit is activated, it will immediately elapse and the configured unit is started\&. This is not the case for timers defined in the other directives\&.
.sp


        These are monotonic timers, independent of wall\-clock time and timezones\&. If the computer is temporarily suspended, the monotonic clock stops too\&.
.sp


        If the empty string is assigned to any of these options, the list of timers is reset, and all prior assignments will have no effect\&.
.sp


        Note that timers do not necessarily expire at the precise time configured with these settings, as they are subject to the
\fIAccuracySec=\fR
setting below\&.


      .RE

      .PP
\fIOnCalendar=\fR
.RS 4

        

        Defines realtime (i\&.e\&. wallclock) timers with calendar event expressions\&. See
\fBsystemd.time\fR(7)
for more information on the syntax of calendar event expressions\&. Otherwise, the semantics are similar to
\fIOnActiveSec=\fR
and related settings\&.
.sp


        Note that timers do not necessarily expire at the precise time configured with this setting, as it is subject to the
\fIAccuracySec=\fR
setting below\&.
.sp


       May be specified more than once\&.

      .RE

      .PP
\fIAccuracySec=\fR
.RS 4

        

        Specify the accuracy the timer shall elapse with\&. Defaults to 1min\&. The timer is scheduled to elapse within a time window starting with the time specified in
\fIOnCalendar=\fR,
\fIOnActiveSec=\fR,
\fIOnBootSec=\fR,
\fIOnStartupSec=\fR,
\fIOnUnitActiveSec=\fR
or
\fIOnUnitInactiveSec=\fR
and ending the time configured with
\fIAccuracySec=\fR
later\&. Within this time window, the expiry time will be placed at a host\-specific, randomized, but stable position that is synchronized between all local timer units\&. This is done in order to optimize power consumption to suppress unnecessary CPU wake\-ups\&. To get best accuracy, set this option to 1us\&. Note that the timer is still subject to the timer slack configured via
\fBsystemd-system.conf\fR(5)\*(Aqs
\fITimerSlackNSec=\fR
setting\&. See
\fBprctl\fR(2)
for details\&. To optimize power consumption, make sure to set this value as high as possible and as low as necessary\&.

      .RE

      .PP
\fIRandomizedDelaySec=\fR
.RS 4

        

        Delay the timer by a randomly selected, evenly distributed amount of time between 0 and the specified time value\&. Defaults to 0, indicating that no randomized delay shall be applied\&. Each timer unit will determine this delay randomly each time it is started, and the delay will simply be added on top of the next determined elapsing time\&. This is useful to stretch dispatching of similarly configured timer events over a certain amount time, to avoid that they all fire at the same time, possibly resulting in resource congestion\&. Note the relation to
\fIAccuracySec=\fR
above: the latter allows the service manager to coalesce timer events within a specified time range in order to minimize wakeups, the former does the opposite: it stretches timer events over a time range, to make it unlikely that they fire simultaneously\&. If
\fIRandomizedDelaySec=\fR
and
\fIAccuracySec=\fR
are used in conjunction, first the randomized delay is added, and then the result is possibly further shifted to coalesce it with other timer events happening on the system\&. As mentioned above
\fIAccuracySec=\fR
defaults to 1min and
\fIRandomizedDelaySec=\fR
to 0, thus encouraging coalescing of timer events\&. In order to optimally stretch timer events over a certain range of time, make sure to set
\fIRandomizedDelaySec=\fR
to a higher value, and
\fIAccuracySec=1us\fR\&.

      .RE

      .PP
\fIUnit=\fR
.RS 4

        

        The unit to activate when this timer elapses\&. The argument is a unit name, whose suffix is not
\&.timer\&. If not specified, this value defaults to a service that has the same name as the timer unit, except for the suffix\&. (See above\&.) It is recommended that the unit name that is activated and the unit name of the timer unit are named identically, except for the suffix\&.

      .RE

      .PP
\fIPersistent=\fR
.RS 4

        

        Takes a boolean argument\&. If true, the time when the service unit was last triggered is stored on disk\&. When the timer is activated, the service unit is triggered immediately if it would have been triggered at least once during the time when the timer was inactive\&. This is useful to catch up on missed runs of the service when the machine was off\&. Note that this setting only has an effect on timers configured with
\fIOnCalendar=\fR\&. Defaults to
\fIfalse\fR\&.

      .RE

      .PP
\fIWakeSystem=\fR
.RS 4

        

        Takes a boolean argument\&. If true, an elapsing timer will cause the system to resume from suspend, should it be suspended and if the system supports this\&. Note that this option will only make sure the system resumes on the appropriate times, it will not take care of suspending it again after any work that is to be done is finished\&. Defaults to
\fIfalse\fR\&.

      .RE

      .PP
\fIRemainAfterElapse=\fR
.RS 4

        

        Takes a boolean argument\&. If true, an elapsed timer will stay loaded, and its state remains queriable\&. If false, an elapsed timer unit that cannot elapse anymore is unloaded\&. Turning this off is particularly useful for transient timer units that shall disappear after they first elapse\&. Note that this setting has an effect on repeatedly starting a timer unit that only elapses once: if
\fIRemainAfterElapse=\fR
is on, it will not be started again, and is guaranteed to elapse only once\&. However, if
\fIRemainAfterElapse=\fR
is off, it might be started again if it is already elapsed, and thus be triggered multiple times\&. Defaults to
\fIyes\fR\&.

      .RE
    
  

  .SH "SEE ALSO"

      
      .PP
\fBsystemd\fR(1),
\fBsystemctl\fR(1),
\fBsystemd.unit\fR(5),
\fBsystemd.service\fR(5),
\fBsystemd.time\fR(7),
\fBsystemd.directives\fR(7),
\fBsystemd-system.conf\fR(5),
\fBprctl\fR(2)

  

