# Automatically generated by gettext-macros.
:
skip_all_ "couldn't find or get gettext macros"
# Even recent versions of gettext used the now-obsolete 'AM_PROG_MKDIR_P'
# m4 macro.  So we need the following to avoid spurious errors.
ACLOCAL="$ACLOCAL -Wno-obsolete"
AUTOMAKE="$AUTOMAKE -Wno-obsolete"
