'\" t
.TH "COREDUMPCTL" "1" "" "systemd 239" "coredumpctl"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------


  

  

  .SH "NAME"
coredumpctl \- Retrieve and process saved core dumps and metadata


  .SH "SYNOPSIS"

    .HP \w'\fBcoredumpctl\fR\ 'u

      \fBcoredumpctl\fR
       [OPTIONS...]
       {COMMAND}
       [PID|COMM|EXE|MATCH...]
    

  

  .SH "DESCRIPTION"

    

    .PP
\fBcoredumpctl\fR
is a tool that can be used to retrieve and process core dumps and metadata which were saved by
\fBsystemd-coredump\fR(8)\&.

  

  .SH "OPTIONS"

    

    .PP
The following options are understood:


    


      .PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4

    
    

    
      Print a short help text and exit\&.

  .RE
      .PP
\fB\-\-version\fR
.RS 4

    

    
      Print a short version string and exit\&.

    
  .RE

      .PP
\fB\-\-no\-legend\fR
.RS 4

        

        Do not print column headers\&.

      .RE

      .PP
\fB\-\-no\-pager\fR
.RS 4

    

    
      Do not pipe output into a pager\&.

    
  .RE

      .PP
\fB\-1\fR
.RS 4

        

        Show information of a single core dump only, instead of listing all known core dumps\&.

      .RE

      .PP
\fB\-S\fR, \fB\-\-since\fR
.RS 4

        
        

        Only print entries which are since the specified date\&.

      .RE

      .PP
\fB\-U\fR, \fB\-\-until\fR
.RS 4

        
        

        Only print entries which are until the specified date\&.

      .RE

      .PP
\fB\-r\fR, \fB\-\-reverse\fR
.RS 4

        
        

        Reverse output so that the newest entries are displayed first\&.

      .RE

      .PP
\fB\-F\fR \fIFIELD\fR, \fB\-\-field=\fR\fIFIELD\fR
.RS 4

        
        

        Print all possible data values the specified field takes in matching core dump entries of the journal\&.

      .RE

      .PP
\fB\-o\fR \fIFILE\fR, \fB\-\-output=\fR\fIFILE\fR
.RS 4

        
        

        Write the core to
\fBFILE\fR\&.

      .RE

      .PP
\fB\-\-debugger=\fR\fIDEBUGGER\fR
.RS 4

        

        Use the given debugger for the
\fBdebug\fR
command\&. If not given and
\fI$SYSTEMD_DEBUGGER\fR
is unset, then
\fBgdb\fR(1)
will be used\&.

      .RE

      .PP
\fB\-D\fR \fIDIR\fR, \fB\-\-directory=\fR\fIDIR\fR
.RS 4

        
        

        Use the journal files in the specified
\fBDIR\fR\&.

      .RE

      .PP
\fB\-q\fR, \fB\-\-quiet\fR
.RS 4

        
        

        Suppresses informational messages about lack of access to journal files and possible in\-flight coredumps\&.

      .RE
    
  

  .SH "COMMANDS"

    

    .PP
The following commands are understood:


    

      .PP
\fBlist\fR
.RS 4

        

        List core dumps captured in the journal matching specified characteristics\&. If no command is specified, this is the implied default\&.
.sp


        The output is designed to be human readable and contains list contains a table with the following columns:

        
          .PP
TIME
.RS 4

            
            The timestamp of the crash, as reported by the kernel\&.

            
          .RE

          .PP
PID
.RS 4

            
            The identifier of the process that crashed\&.

            
          .RE

          .PP
UID, GID
.RS 4

            
            
            The user and group identifiers of the process that crashed\&.

            
          .RE

          .PP
SIGNAL
.RS 4

            
            The signal that caused the process to crash, when applicable\&.

          .RE

          .PP
COREFILE
.RS 4

            
            Information whether the coredump was stored, and whether it is still accessible:
none
means the core was not stored,
\-
means that it was not available (for example because the process was not terminated by a signal),
present
means that the core file is accessible by the current user,
journal
means that the core was stored in the
journal,
truncated
is the same as one of the previous two, but the core was too large and was not stored in its entirety,
error
means that the core file cannot be accessed, most likely because of insufficient permissions, and
missing
means that the core was stored in a file, but this file has since been removed\&.

          .RE

          .PP
EXE
.RS 4

            
            The full path to the executable\&. For backtraces of scripts this is the name of the interpreter\&.

          .RE
        .sp


        It\*(Aqs worth noting that different restrictions apply to data saved in the journal and core dump files saved in
/var/lib/systemd/coredump, see overview in
\fBsystemd-coredump\fR(8)\&. Thus it may very well happen that a particular core dump is still listed in the journal while its corresponding core dump file has already been removed\&.

      .RE

      .PP
\fBinfo\fR
.RS 4

        

        Show detailed information about core dumps captured in the journal\&.

      .RE

      .PP
\fBdump\fR
.RS 4

        

        Extract the last core dump matching specified characteristics\&. The core dump will be written on standard output, unless an output file is specified with
\fB\-\-output=\fR\&.

      .RE

      .PP
\fBdebug\fR
.RS 4

        

        Invoke a debugger on the last core dump matching specified characteristics\&. By default,
\fBgdb\fR(1)
will be used\&. This may be changed using the
\fB\-\-debugger=\fR
option or the
\fI$SYSTEMD_DEBUGGER\fR
environment variable\&.

      .RE

    

  

  .SH "MATCHING"

    

    .PP
A match can be:


    

      .PP
\fIPID\fR
.RS 4

        

        Process ID of the process that dumped core\&. An integer\&.

      .RE

      .PP
\fICOMM\fR
.RS 4

        

        Name of the executable (matches
\fBCOREDUMP_COMM=\fR)\&. Must not contain slashes\&.

      .RE

      .PP
\fIEXE\fR
.RS 4

        

        Path to the executable (matches
\fBCOREDUMP_EXE=\fR)\&. Must contain at least one slash\&.

      .RE

      .PP
\fIMATCH\fR
.RS 4

        

        General journalctl match filter, must contain an equals sign (=)\&. See
\fBjournalctl\fR(1)\&.

      .RE
    
  

  .SH "EXIT STATUS"

    
    .PP
On success, 0 is returned; otherwise, a non\-zero failure code is returned\&. Not finding any matching core dumps is treated as failure\&.

  

  .SH "ENVIRONMENT"

    

    

      .PP
\fI$SYSTEMD_DEBUGGER\fR
.RS 4

        
        Use the given debugger for the
\fBdebug\fR
command\&. See the
\fB\-\-debugger=\fR
option\&.

      .RE
    
  

  .SH "EXAMPLES"

    

    .PP
\fBExample\ \&1.\ \&List all the core dumps of a program named foo\fR

      

      
.sp
.if n \{\
.RS 4
.\}
.nf
# coredumpctl list foo
.fi
.if n \{\
.RE
.\}
.sp

    


    .PP
\fBExample\ \&2.\ \&Invoke gdb on the last core dump\fR

      

      
.sp
.if n \{\
.RS 4
.\}
.nf
# coredumpctl debug
.fi
.if n \{\
.RE
.\}
.sp

    


    .PP
\fBExample\ \&3.\ \&Show information about a process that dumped core, matching by its PID 6654\fR

      

      
.sp
.if n \{\
.RS 4
.\}
.nf
# coredumpctl info 6654
.fi
.if n \{\
.RE
.\}
.sp

    


    .PP
\fBExample\ \&4.\ \&Extract the last core dump of /usr/bin/bar to a file named bar\&.coredump\fR

      

      
.sp
.if n \{\
.RS 4
.\}
.nf
# coredumpctl \-o bar\&.coredump dump /usr/bin/bar
.fi
.if n \{\
.RE
.\}
.sp

    

  

  .SH "SEE ALSO"

    
    .PP
\fBsystemd-coredump\fR(8),
\fBcoredump.conf\fR(5),
\fBsystemd-journald.service\fR(8),
\fBgdb\fR(1)

  

